In [1]:
import pandas as pd
import ast

In [2]:
data = pd.read_excel(r"F:\GUVI\Project\Car Dekho\DATA\chennai_cars.xlsx")

In [3]:
data.drop(['car_links','new_car_feature'], axis=1, inplace=True)

In [4]:
# first columns name

data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
new_car_detail_df = pd.json_normalize(data['new_car_detail'])

In [5]:
# removing the column name and adding the new columns in old data

data = pd.concat([data.drop(columns=['new_car_detail']), new_car_detail_df], axis=1)


# First column over

In [6]:
# second columns

data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
new_car_overview_df = pd.json_normalize(data['new_car_overview'])

In [7]:
# find the column name top in second columns in old data

def expand(column):
    top_data = column['top']
    dict = {item['key'] : item['value'] for item in top_data}
    return pd.Series(dict)

new_columns = new_car_overview_df.apply(expand, axis=1)

In [8]:
# removing the column top in df and adding the new_columns data

new_car_overview_df = pd.concat([new_car_overview_df.drop(columns=['top']), new_columns], axis=1)

In [9]:
# removing the column in old data and adding the df

data = pd.concat([data.drop(columns=['new_car_overview']), new_car_overview_df], axis=1)

In [10]:
# third columns

data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)
new_car_specs_df = pd.json_normalize(data['new_car_specs'])

In [11]:
new_columns = new_car_specs_df.apply(expand, axis=1)

In [12]:
new_car_specs_df = pd.concat([new_car_specs_df.drop(columns=['top']), new_columns], axis=1)

In [13]:
flattened_data = []

for car_spec in data['new_car_specs']:

    new_car_specs_data_df = {}

    for category in car_spec['data']:
        for item in category['list']:
            new_car_specs_data_df[item['key']] = item['value']

    flattened_data.append(new_car_specs_data_df)

df = pd.DataFrame(flattened_data)

In [14]:
new_car_specs_df = pd.concat([new_car_specs_df.drop(columns=['data']),df], axis=1)

In [15]:
data = pd.concat([data.drop(columns=['new_car_specs']),new_car_specs_df], axis=1)

In [16]:
data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Compression Ratio,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,9.9:1,No,1280mm,1290mm,1540kg,4.5 metres,145 Kmph,15.7 Seconds,NaN,NaN
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,NaN,No,NaN,NaN,NaN,5.0,NaN,11.7,72.2 x 81.3,NaN
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,NaN,No,1400mm,1385mm,NaN,4.7 metres,165 Kmph,14.3 Seconds,NaN,NaN
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,NaN,No,NaN,NaN,NaN,5.1 meters,172 Kmph,13.7 Seconds,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,NaN,No,1530mm,1530mm,1315kg,4.8 Meters,NaN,NaN,NaN,NaN
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,NaN,No,1560mm,1567mm,1777kg,5.2 metres,156 Kmph,13.9 Seconds,NaN,NaN
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,NaN,No,1540 mm,1530 mm,NaN,5.1m,154.19 kmph,NaN,77x85.8,209 mm
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,NaN,No,1578mm,1568mm,2250kg,5.75meters,NaN,NaN,74.5 x 81 mm,NaN
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,NaN,No,1541 mm,1581 mm,NaN,5.5 metres,226 Kmph,7.7 Seconds,NaN,NaN

In [17]:
data['City'] = "chennai"

In [19]:
data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,City
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,No,1280mm,1290mm,1540kg,4.5 metres,145 Kmph,15.7 Seconds,NaN,NaN,chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,No,NaN,NaN,NaN,5.0,NaN,11.7,72.2 x 81.3,NaN,chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,No,1400mm,1385mm,NaN,4.7 metres,165 Kmph,14.3 Seconds,NaN,NaN,chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,No,NaN,NaN,NaN,5.1 meters,172 Kmph,13.7 Seconds,NaN,NaN,chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,No,1530mm,1530mm,1315kg,4.8 Meters,NaN,NaN,NaN,NaN,chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,No,1560mm,1567mm,1777kg,5.2 metres,156 Kmph,13.9 Seconds,NaN,NaN,chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,No,1540 mm,1530 mm,NaN,5.1m,154.19 kmph,NaN,77x85.8,209 mm,chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,No,1578mm,1568mm,2250kg,5.75meters,NaN,NaN,74.5 x 81 mm,NaN,chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,No,1541 mm,1581 mm,NaN,5.5 metres,226 Kmph,7.7 Seconds,NaN,NaN,chennai

In [18]:
data.to_csv("cleaned_chennai_cars.csv")